"""workout_location

Revision ID: 07b2fa7049e9
Revises: 909a935138ed
Create Date: 2024-06-15 05:40:35.343293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b2fa7049e9'
down_revision: Union[str, None] = '909a935138ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('location', sa.String(), nullable=True))
    op.add_column('workout', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'city')
    op.drop_column('workout', 'location')
    # ### end Alembic commands ###
