"""custom_user_exercise

Revision ID: 1112b6a07df6
Revises: 64d4dae27c26
Create Date: 2025-04-22 04:34:03.908742

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1112b6a07df6"
down_revision: Union[str, None] = "64d4dae27c26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_user_exercise",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("equipment", sa.Text(), nullable=True),
        sa.Column("muscle_group", sa.Text(), nullable=True),
        sa.Column("metric_type", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("custom_user_exercise")
    # ### end Alembic commands ###
