"""privacy_settings

Revision ID: 51fbc74f41a7
Revises: dece2e184b25
Create Date: 2025-03-03 02:02:41.805568

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "51fbc74f41a7"
down_revision: Union[str, None] = "dece2e184b25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    privacy_setting_enum = sa.Enum("public", "private", name="privacysettingenum")
    privacy_setting_enum.create(op.get_bind())

    op.add_column(
        "user",
        sa.Column(
            "privacy_setting",
            sa.Enum("public", "private", name="privacysettingenum"),
            server_default=sa.text(
                "'public'"
            ),  # Correct way to set a default in Alembic
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "privacy_setting")
    privacy_setting_enum = sa.Enum("public", "private", name="privacysettingenum")
    privacy_setting_enum.drop(op.get_bind())
    # ### end Alembic commands ###
