"""user_block

Revision ID: 64d4dae27c26
Revises: 7f295f9c9735
Create Date: 2025-04-06 23:12:41.583291

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64d4dae27c26"
down_revision: Union[str, None] = "7f295f9c9735"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_block",
        sa.Column("blocker_id", sa.UUID(), nullable=False),
        sa.Column("blocked_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["blocked_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["blocker_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("blocker_id", "blocked_id", name="unique_user_block"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_block")
    # ### end Alembic commands ###
