"""workout_set

Revision ID: 69ec70663d2e
Revises: 1112b6a07df6
Create Date: 2025-04-22 04:56:34.336583

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69ec70663d2e"
down_revision: Union[str, None] = "1112b6a07df6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workout_set",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workout_id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.UUID(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "weight_unit", sa.Enum("kg", "lbs", name="weightunitenum"), nullable=True
        ),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.Column(
            "distance_unit",
            sa.Enum("meters", "kilometers", "miles", "yards", name="distanceunitenum"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"], ["custom_user_exercise.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["workout_id"], ["workout.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workout_set")
    # ### end Alembic commands ###
