"""follow_status

Revision ID: 7fcaa7338ec2
Revises: 51fbc74f41a7
Create Date: 2025-03-03 20:30:38.604540

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7fcaa7338ec2"
down_revision: Union[str, None] = "51fbc74f41a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    follow_status_enum = sa.Enum("pending", "accepted", name="followstatusenum")
    follow_status_enum.create(op.get_bind())

    op.add_column(
        "follower",
        sa.Column(
            "status",
            sa.Enum("pending", "accepted", name="followstatusenum"),
            server_default=sa.text("'accepted'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("follower", "status")
    # ### end Alembic commands ###
