"""datetime for workouts

Revision ID: 8be323ef6ed0
Revises: 66c97d299e26
Create Date: 2024-05-19 04:26:35.195323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8be323ef6ed0'
down_revision: Union[str, None] = '66c97d299e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.drop_column('workout', 'date')
    op.drop_column('workout', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('workout', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('workout', 'datetime')
    # ### end Alembic commands ###
