"""workout_intensity

Revision ID: 9a4701abcd12
Revises: deb7ded65fcf
Create Date: 2025-04-30 03:56:23.810524

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a4701abcd12"
down_revision: Union[str, None] = "deb7ded65fcf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workout", sa.Column("intensity", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workout", "intensity")
    # ### end Alembic commands ###
