"""unique_friendships

Revision ID: a3ea1f238dc4
Revises: 656af406e20b
Create Date: 2024-05-21 02:02:39.320683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ea1f238dc4'
down_revision: Union[str, None] = '656af406e20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_friendship', 'friendship', ['sender_id', 'recipient_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_friendship', 'friendship', type_='unique')
    # ### end Alembic commands ###
