"""workout_exercises

Revision ID: af0cdee4304e
Revises: 7fcaa7338ec2
Create Date: 2025-03-20 03:18:13.748396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af0cdee4304e"
down_revision: Union[str, None] = "7fcaa7338ec2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workout_exercise",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workout_id", sa.UUID(), nullable=False),
        sa.Column("exercise_name", sa.String(), nullable=False),
        sa.Column("sets", sa.Integer(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.Column(
            "weight_unit", sa.Enum("kg", "lbs", name="weightunitsenum"), nullable=True
        ),
        sa.ForeignKeyConstraint(["workout_id"], ["workout.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workout_exercise")
    # ### end Alembic commands ###
