"""workout_date_mando

Revision ID: cf57cefad76c
Revises: 9a4701abcd12
Create Date: 2025-05-19 03:06:12.044559

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cf57cefad76c"
down_revision: Union[str, None] = "9a4701abcd12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workout", "datetime", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workout", "datetime", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###
