"""cascade_workout_deletes

Revision ID: dece2e184b25
Revises: fc212e1b313a
Create Date: 2025-02-12 22:31:49.648410

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dece2e184b25"
down_revision: Union[str, None] = "fc212e1b313a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("comment_user_id_fkey", "comment", type_="foreignkey")
    op.drop_constraint("comment_workout_id_fkey", "comment", type_="foreignkey")
    op.create_foreign_key(
        None, "comment", "workout", ["workout_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "comment", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("like_user_id_fkey", "like", type_="foreignkey")
    op.drop_constraint("like_workout_id_fkey", "like", type_="foreignkey")
    op.create_foreign_key(None, "like", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(
        None, "like", "workout", ["workout_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "like", type_="foreignkey")
    op.drop_constraint(None, "like", type_="foreignkey")
    op.create_foreign_key(
        "like_workout_id_fkey", "like", "workout", ["workout_id"], ["id"]
    )
    op.create_foreign_key("like_user_id_fkey", "like", "user", ["user_id"], ["id"])
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.create_foreign_key(
        "comment_workout_id_fkey", "comment", "workout", ["workout_id"], ["id"]
    )
    op.create_foreign_key(
        "comment_user_id_fkey", "comment", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
