"""unique_attendee

Revision ID: f2646f3ec76c
Revises: a3ea1f238dc4
Create Date: 2024-05-22 05:15:17.878653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2646f3ec76c'
down_revision: Union[str, None] = 'a3ea1f238dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_attendee', 'attendee', ['user_id', 'workout_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_attendee', 'attendee', type_='unique')
    # ### end Alembic commands ###
