"""add_user_device

Revision ID: fc212e1b313a
Revises: e9eb13fc08ec
Create Date: 2025-02-10 06:16:46.397639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc212e1b313a"
down_revision: Union[str, None] = "e9eb13fc08ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_device",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("device_token", sa.String(), nullable=False),
        sa.Column("endpoint_arn", sa.String(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_token"),
        sa.UniqueConstraint("endpoint_arn"),
    )
    op.create_index(
        op.f("ix_user_device_user_id"), "user_device", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_device_user_id"), table_name="user_device")
    op.drop_table("user_device")
    # ### end Alembic commands ###
